Add slight modification to whatsmyip script
Script error is no less ambiguous and more descriptive.

diff --git a/bin/whatsmyip b/bin/whatsmyip
--- a/bin/whatsmyip
+++ b/bin/whatsmyip
@@ -3,5 +3,6 @@
 if [ ! -z $(which curl) ]; then
    curl --silent icanhazip.com
 else
-  echo "curl: could not be found"
+  echo "error: curl could not be found on in PATH"
+  exit 1
 fi
